fn main() -> Result<(), Box<dyn std::error::Error>> {
    tonic_build::configure()
        .build_server(true)
        .out_dir("src")
        .compile(
            &[
                "protos/network.proto",
                "protos/transaction.proto",
                "protos/block.proto",
                "protos/storage.proto",
                "protos/consensus.proto",
                "protos/overlay.proto",
                "protos/validation.proto",
                "protos/mining.proto",
                "protos/auth.proto",
                "protos/alert.proto",
                "protos/index.proto",
                "protos/metrics.proto",
            ],
            &["protos"],
        )?;
    Ok(())
}
