[package]
name = "shared"
version = "0.3.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
bincode = { workspace = true }
tracing = { workspace = true }
toml = { workspace = true }

[lib]
name = "shared"
path = "src/lib.rs"
